nodeLinker: node-modules

npmScopes:
  red-technology:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAuthToken: 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

yarnPath: .yarn/releases/yarn-4.0.1.cjs
